//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaNexox.DTOs.DBPruebaNexos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PruebaNexosEntities : DbContext
    {
        public PruebaNexosEntities()
            : base("name=PruebaNexosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblAutoresLibros> TblAutoresLibros { get; set; }
        public virtual DbSet<TblConfigLimit> TblConfigLimit { get; set; }
        public virtual DbSet<TblGeneros> TblGeneros { get; set; }
        public virtual DbSet<TblLibros> TblLibros { get; set; }
    }
}
