//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaNexox.DTOs.DBPruebaNexos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAutoresLibros
    {
        public int IdAutorLibro { get; set; }
        public int IdLibro { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Email { get; set; }
        public System.DateTime FechaCreación { get; set; }
        public string CiudadProcedencia { get; set; }
    
        public virtual TblLibros TblLibros { get; set; }
    }
}
