//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaNexox.DTOs.DBPruebaNexos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLibros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblLibros()
        {
            this.TblAutoresLibros = new HashSet<TblAutoresLibros>();
        }
    
        public int IdLibro { get; set; }
        public string Titulo { get; set; }
        public int Año { get; set; }
        public int IdGenero { get; set; }
        public int NumeroPaginas { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAutoresLibros> TblAutoresLibros { get; set; }
        public virtual TblGeneros TblGeneros { get; set; }
    }
}
